chore(*): update deployment script

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -4,63 +4,130 @@ cd `dirname $0`/..
 
 export DOTFILES=`pwd`
 
+echo '               _      _'
+echo '   |          | | o  | |'
+echo ' __|   __ _|_ | |    | |  _   ,'
+echo '/  |  /  \_|  |/  |  |/  |/  / \_'
+echo '\_/|_/\__/ |_/|__/|_/|__/|__/ \/'
+echo '              |\'
+echo '              |/'
+
+echo; echo 'Locating your home directory...'; echo
+
 if [ -z ${HOME:+_} ]
   then
-    echo 'Please enter your username:'
+    echo 'Home directory not set, please enter your username:'
 
-    read HOME && HOME=/Users/$HOME
+    read HOME && HOME=/Users/$HOME; echo
 
     if [ ! -d $HOME ]
       then
-        echo "$HOME: directory not found" >&2
+        echo 'Error! Unable to locate your home directory --' >&2
+        echo "$HOME: directory not found" >&2; echo
         exit 1
     fi
+
+    echo "Success! Setting $HOME as your home directory..."; echo
 
     export HOME=$HOME
 fi
 
-export TARGET=$HOME
+echo 'Initializing...'; echo
+
+REAL_HOME=$HOME
+
 export HOME=$DOTFILES/deploy
 export PATH=/usr/bin:/bin:/usr/sbin:/sbin
 
+echo 'Loading profile...'; echo
+
 . $HOME/.profile
 
-if ! available curl || ! available /usr/bin/ruby
+export HOME=$REAL_HOME
+
+unset REAL_HOME
+
+echo 'Validating dependencies...'; echo
+
+if ! available curl || ! available ruby
   then
-    exit 1
+    echo '-- Error! Could not validate dependencies.' >&2
+    echo; exit 1
 fi
 
 if ! available brew
   then
-    /usr/bin/ruby -e `curl -fLSs https://raw.githubusercontent.com/Homebrew/install/master/install`
+    echo 'Installing Homebrew...'; echo
+
+    ruby -e `curl -fLSs https://raw.githubusercontent.com/Homebrew/install/master/install`
 
     if [ $? -ne 0 ]
       then
-        exit 1
+        echo '-- Error! Unable to install Homebrew.' >&2
+        echo; exit 1
     fi
 fi
 
+echo 'Updating Homebrew...'; echo
+
 brew update >/dev/null 2>&1
 
+echo 'Upgrading outdated brews...'; echo
+
 brew upgrade >/dev/null 2>&1
+
+echo 'Installing dependencies...'; echo
 
 brew install git node ruby zsh
 
 if [ $? -ne 0 ]
   then
-    exit 1
+    echo '-- Error! Unable to install dependencies.' >&2
+    echo; exit 1
 fi
 
-brew cleanup >/dev/null 2>&1
+echo; brew cleanup >/dev/null 2>&1
 
-git checkout master
+echo 'Validating Oh-My-Zsh...'; echo
 
-git pull origin master
+if [ -d $HOME/.oh-my-zsh ]
+  then
+    echo 'Updating Oh-My-Zsh...'; echo
+
+    cd $HOME/.oh-my-zsh
+
+    git checkout master && git pull origin master
+
+    if [ $? -ne 0 ]
+      then
+        echo '-- Error! Unable to update Oh-My-Zsh.' >&2
+        echo; exit 1
+    fi
+
+    echo; cd $DOTFILES
+else
+  echo 'Installing Oh-My-Zsh...'; echo
+
+  git clone git://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh
+
+  if [ $? -ne 0 ]
+    then
+      echo '-- Error! Unable to install Oh-My-Zsh.' >&2
+      echo; exit 1
+  fi
+fi
+
+echo 'Updating dotfiles...'; echo
+
+git checkout master && git pull origin master
 
 if [ $? -ne 0 ]
   then
-    exit 1
+    echo '-- Error! Unable to update dotfiles.' >&2
+    echo; exit 1
 fi
+
+echo; echo 'Updating npm...'; echo
 
 ni -g npm && npm update -g
 
